deploy_ingress:
	kubectl apply -f traefik/role.yml
	kubectl apply -f traefik/role-binding.yml
	kubectl apply -f traefik/serviceaccount.yml
	kubectl apply -f traefik/traefik-services.yml
	kubectl apply -f traefik/traefik.yml

delete_ingress:
	kubectl delete -f traefik/role.yml
	kubectl delete -f traefik/role-binding.yml
	kubectl delete -f traefik/serviceaccount.yml
	kubectl delete -f traefik/traefik-services.yml
	kubectl delete -f traefik/traefik-binding.yml