apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: ingress-nginx
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30006