---
apiVersion: v1
kind: Secret 
metadata:
  name: mariadb-secret
  namespace: default
type: Opaque
data:
  mariadb-root-password: d0VsY29tZS4wMUs=
  
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-user
  namespace: default
type: Opaque
data:
  mariadb-username:  cm9vdA==

