---
apiVersion: v1
kind: Secret 
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  postgres-password: d0VsY29tZS4wMUs=
  
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-user
  namespace: default
type: Opaque
data:
  postgres-username:  cG9zdGdyZXM=

