---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: default
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: default
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik