---
services:
  liferay:
    image: liferay/portal:7.4.3.19-ga19
    container_name: liferay
    networks:
      - liferay's_network
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - liferay-data:/opt/liferay/data
      - liferay-osgi-configs:/opt/liferay/osgi/configs
      - liferay-osgi-marketplace:/opt/liferay/osgi/marketplace
      - liferay-osgi-modules:/opt/liferay/osgi/modules
      - liferay-osgi-war:/opt/liferay/osgi/war
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    networks:
      - liferay's_network
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: liferay
      MYSQL_DATABASE: liferay
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    networks:
      - liferay's_network
    ports:
      - 8081:8081
    environment:
      # KC_PROXY_ADDRESS_FORWARDING:true
      # KC_HOSTNAME_STRICT:false
      # KC_HOSTNAME:keycloak.jimsgarage.co.uk
      # KC_PROXY:edge
      # KC_HTTP_ENABLED:true
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: SUPERsecret
      KC_DB_URL_HOST: mariadb
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: liferay
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_PORT: 8081
      KC_LOG_LEVEL: info
    command:  ["start-dev", "--http-port", "8081"]
    restart: unless-stopped

networks:
  liferay's_network:
    dirver: bridge

volumes:
  liferay-data:
  liferay-osgi-configs:
  liferay-osgi-marketplace:
  liferay-osgi-modules:
  liferay-osgi-war:
  mariadb-data:
