---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-data
  namespace: default
  labels:
    app: liferay-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/liferay/data/document_library  # Changed from /mnt/liferay/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-data-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-osgi-configs
  namespace: default
  labels:
    app: liferay-osgi-configs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/liferay/osgi-configs  # Changed from /mnt/liferay/osgi-configs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-osgi-configs-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-osgi-marketplace
  namespace: default
  labels:
    app: liferay-osgi-marketplace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/liferay/osgi-marketplace/override  # Changed from /mnt/liferay/osgi-marketplace

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-osgi-marketplace-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-osgi-modules
  namespace: default
  labels:
    app: liferay-osgi-modules
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/liferay/osgi-modules  # Changed from /mnt/liferay/osgi-modules

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-osgi-modules-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-osgi-war
  namespace: default
  labels:
    app: liferay-osgi-war
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/liferay/osgi-war  # Changed from /mnt/liferay/osgi-war

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-osgi-war-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
