---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-pv
  namespace: default
  labels:
    app: liferay-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/liferay
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
