---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db_url
data:
  DB_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_USER_DATABASE}?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"