---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liferay-deployment
  namespace: default
  labels:
    app: liferay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferay
  template:
    metadata:
      labels:
        app: liferay
    spec:
      containers:
      - name: liferay
        image: liferay/portal:latest
        ports: 
          - containerPort: 8080
          - containerPort: 8000
          - containerPort: 11311
        # env:
        #   # - name: LIFERAY_JVM_OPTS
        #   #   value: -Xms8g -Xmx8g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
        #   - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME
        #     value: org.postgresql.Driver
        #   - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL
        #     value: "jdbc:postgresql://postgres-service:5432/liferay"
        #   - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME
        #     valueFrom:
        #       secretKeyRef:
        #         name: postgres-user
        #         key: postgres-username
        #   - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: postgres-secret
        #         key: postgres-password
        resources:
          requests:
            memory: "4Gi"
            cpu: "3"
          limits:
            memory: "4Gi"
            cpu: "3"
        volumeMounts:
          - name: liferay-data
            mountPath: /opt/liferay/data/document_library
          - name: liferay-osgi-configs
            mountPath: /opt/liferay/osgi/configs
          - name: liferay-osgi-marketplace
            mountPath: /opt/liferay/osgi/marketplace/override
          - name: liferay-osgi-modules
            mountPath: /opt/liferay/osgi/modules
          - name: liferay-osgi-war
            mountPath: /opt/liferay/osgi/war
      volumes:
        - name: liferay-mount
          hostPath:
            path: /mnt/liferay
            type: Directory
        - name: liferay-data
          persistentVolumeClaim:
            claimName: liferay-data-pvc
        - name: liferay-osgi-configs
          persistentVolumeClaim:
            claimName: liferay-osgi-configs-pvc
        - name: liferay-osgi-marketplace
          persistentVolumeClaim:
            claimName: liferay-osgi-marketplace-pvc
        - name: liferay-osgi-modules
          persistentVolumeClaim:
            claimName: liferay-osgi-modules-pvc
        - name: liferay-osgi-war
          persistentVolumeClaim:
            claimName: liferay-osgi-war-pvc