---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liferay-deployment
  namespace: default
  labels:
    app: liferay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferay
  template:
    metadata:
      labels:
        app: liferay
    spec:
      containers:
      - name: liferay
        image:  liferay/portal:latest
        ports: 
          - containerPort: 8088
          - containerPort: 8000
          - containerPort: 11311
        env:
          - name: LIFERAY_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
          - name: LIFERAY_VIRTUAL_PERIOD_HOSTS_PERIOD_VALID_PERIOD_HOSTS
            value: "*"
          - name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_HTTP_PERIOD_PORT
            value: "8088" 
          - name: LIFERAY_JVM_OPTS
            value: -Xms2g -Xmx2g 
          - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME
            value: org.postgresql.Driver
          - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL
            value: "jdbc:postgresql://postgres-service.default.svc.cluster.local:5432/liferay"
          - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-user
                key: postgres-username
          - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: LIFERAY_ELASTICSEARCH_ENABLED
            value: "false"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
        #   limits:
        #     memory: "4Gi"
        #     cpu: "2"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 20
        #   timeoutSeconds: 1
        #   periodSeconds: 20
        #   successThreshold: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /portal/health
        #     port: 8080
        #   initialDelaySeconds: 120
        #   timeoutSeconds: 1
        #   periodSeconds: 15
        #   successThreshold: 3
        #   failureThreshold: 3
        volumeMounts:
          - name: liferay-data
            mountPath: /opt/liferay/data
          - name: liferay-config
            mountPath: /mnt/liferay/config
      volumes:
      - name: liferay-data
        persistentVolumeClaim:
          claimName: liferay-data
      - name: liferay-config
        persistentVolumeClaim:
          claimName: liferay-config