---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: default
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template: 
    metadata:
      labels:
        app: mariadb 
    spec: 
      containers:
      - name: mariadb
        image: mariadb:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306 
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        - name: MARIADB_DATABASE
          value: keycloakDB
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-user
              key:  mariadb-username
        volumeMounts:
        - name: mariadb-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-pvc
