---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: postgres-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key:  postgres-username
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key:  postgres-username
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  postgres-password
            # - name: POSTGRES_HOST_AUTH_METHOD
            #   value: "md5"
            - name: POSTGRES_DB
              value: liferay
            - name:  PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: PGHOST
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data/pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc