---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: default
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30003
  type: NodePort