---
apiVersion: v1
kind: Service
metadata:
  name: liferay-service
  namespace: default
spec:
  selector:
    app: liferay
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30001
    # - name: debug
    #   protocol: TCP
    #   port: 8000
    #   targetPort: 8000
    #   nodePort: 30002
    # - name: service
    #   protocol: TCP
    #   port: 11311
    #   targetPort: 11311
    #   nodePort: 30003
  type: NodePort
