---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-internal-service
  namespace: ingress-nginx
spec:
  selector:
    app: mariadb
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30004